### ISSUE TITLE
Update `msal-browser` dependency

### ISSUE THREAD

**Issue by Zazo032** [Earlybyte/aad_oauth#235]
The examples are currently using a version (`2.13.1`) from April 1st 2021, I could make the plugin work with version `2.14.1`, but using `2.14.2` breaks the plugin with this error:
```
Uncaught (in promise) ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
    at t [as constructor] (msal-browser.min.js:35:165)
    at new t (msal-browser.min.js:35:6501)
    at t.createEndpointDiscoveryIncompleteError (msal-browser.min.js:35:7025)
    at Function.<anonymous> (msal-browser.min.js:56:11238)
    at msal-browser.min.js:32:1867
    at Object.throw (msal-browser.min.js:32:1972)
    at c (msal-browser.min.js:32:762)
t @ msal-browser.min.js:35
t @ 
```

**Comment by Zazo032** [comment]
All versions above 2.14.1 were throwing errors, at least on B2C. I created #236 to fix those B2C errors
