### ISSUE TITLE
Kindly include support for Flutter Web

### ISSUE THREAD

**Issue by prajothpdw** [Earlybyte/aad_oauth#87]
I do not see any libraries supporting AAD for Flutter Web. This package works like a charm on mobile. Please include support for Flutter web. Thank you,

**Comment by harrbca** [comment]
Did you encounter this issue:

Error: Unsupported operation: Platform._operatingSystem
    at Object.throw_ [as throw] (http://localhost:54904/dart_sdk.js:4354:11)
    at Function._operatingSystem (http://localhost:54904/dart_sdk.js:55038:17)
    at Function.get operatingSystem [as operatingSystem] (http://localhost:54904/dart_sdk.js:55084:27)
    at get _operatingSystem (http://localhost:54904/dart_sdk.js:54997:27)
    at Function.desc.get [as _operatingSystem] (http://localhost:54904/dart_sdk.js:4848:17)
    at get isIOS (http://localhost:54904/dart_sdk.js:55021:26)
    at Function.desc.get [as isIOS] (http://localhost:54904/dart_sdk.js:4848:17)
    at flutter_secure_storage.FlutterSecureStorage.new.[_selectOptions] (http://localhost:54904/packages/flutter_secure_storage/flutter_secure_storage.dart.lib.js:133:36)
    at flutter_secure_storage.FlutterSecureStorage.new.delete (http://localhost:54904/packages/flutter_secure_storage/flutter_secure_storage.dart.lib.js:116:187)
    at auth_storage.AuthStorage.new.clear (http://localhost:54904/packages/aad_oauth/helper/auth_storage.dart.lib.js:46:36)
    at clear.next (<anonymous>)
    at runBody (http://localhost:54904/dart_sdk.js:38020:34)
    at Object._async [as async] (http://localhost:54904/dart_sdk.js:38051:7)
    at auth_storage.AuthStorage.new.clear (http://localhost:54904/packages/aad_oauth/helper/auth_storage.dart.lib.js:45:20)
    at aad_oauth.AadOAuth.new.logout (http://localhost:54904/packages/aad_oauth/aad_oauth.dart.lib.js:53:34)
    at logout.next (<anonymous>)
    at runBody (http://localhost:54904/dart_sdk.js:38020:34)
    at Object._async [as async] (http://localhost:54904/dart_sdk.js:38051:7)
    at aad_oauth.AadOAuth.new.logout (http://localhost:54904/packages/aad_oauth/aad_oauth.dart.lib.js:52:20)
    at aad_oauth.AadOAuth.new._removeOldTokenOnFirstLogin (http://localhost:54904/packages/aad_oauth/aad_oauth.dart.lib.js:103:16)
    at _removeOldTokenOnFirstLogin.next (<anonymous>)
    at http://localhost:54904/dart_sdk.js:38000:33
    at _RootZone.runUnary (http://localhost:54904/dart_sdk.js:37854:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:54904/dart_sdk.js:32815:29)
    at handleValueCallback (http://localhost:54904/dart_sdk.js:33363:49)
    at Function._propagateToListeners (http://localhost:54904/dart_sdk.js:33401:17)
    at _Future.new.[_completeWithValue] (http://localhost:54904/dart_sdk.js:33243:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54904/dart_sdk.js:33266:35)
    at Object._microtaskLoop (http://localhost:54904/dart_sdk.js:38115:13)
    at _startMicrotaskLoop (http://localhost:54904/dart_sdk.js:38121:13)
    at http://localhost:54904/dart_sdk.js:33618:9

**Comment by prajothpdw** [comment]
> Did you encounter this issue:
> 
> Error: Unsupported operation: Platform._operatingSystem at Object.throw_ [as throw] (http://localhost:54904/dart_sdk.js:4354:11)
> at Function._operatingSystem (http://localhost:54904/dart_sdk.js:55038:17)
> at Function.get operatingSystem [as operatingSystem] (http://localhost:54904/dart_sdk.js:55084:27)
> at get _operatingSystem (http://localhost:54904/dart_sdk.js:54997:27)
> at Function.desc.get [as _operatingSystem] (http://localhost:54904/dart_sdk.js:4848:17)
> at get isIOS (http://localhost:54904/dart_sdk.js:55021:26)
> at Function.desc.get [as isIOS] (http://localhost:54904/dart_sdk.js:4848:17)
> at flutter_secure_storage.FlutterSecureStorage.new.[_selectOptions] (http://localhost:54904/packages/flutter_secure_storage/flutter_secure_storage.dart.lib.js:133:36)
> at flutter_secure_storage.FlutterSecureStorage.new.delete (http://localhost:54904/packages/flutter_secure_storage/flutter_secure_storage.dart.lib.js:116:187)
> at auth_storage.AuthStorage.new.clear (http://localhost:54904/packages/aad_oauth/helper/auth_storage.dart.lib.js:46:36)
> at clear.next ()
> at runBody (http://localhost:54904/dart_sdk.js:38020:34)
> at Object._async [as async] (http://localhost:54904/dart_sdk.js:38051:7)
> at auth_storage.AuthStorage.new.clear (http://localhost:54904/packages/aad_oauth/helper/auth_storage.dart.lib.js:45:20)
> at aad_oauth.AadOAuth.new.logout (http://localhost:54904/packages/aad_oauth/aad_oauth.dart.lib.js:53:34)
> at logout.next ()
> at runBody (http://localhost:54904/dart_sdk.js:38020:34)
> at Object._async [as async] (http://localhost:54904/dart_sdk.js:38051:7)
> at aad_oauth.AadOAuth.new.logout (http://localhost:54904/packages/aad_oauth/aad_oauth.dart.lib.js:52:20)
> at aad_oauth.AadOAuth.new._removeOldTokenOnFirstLogin (http://localhost:54904/packages/aad_oauth/aad_oauth.dart.lib.js:103:16)
> at _removeOldTokenOnFirstLogin.next ()
> at http://localhost:54904/dart_sdk.js:38000:33
> at _RootZone.runUnary (http://localhost:54904/dart_sdk.js:37854:58)
> at _FutureListener.thenAwait.handleValue (http://localhost:54904/dart_sdk.js:32815:29)
> at handleValueCallback (http://localhost:54904/dart_sdk.js:33363:49)
> at Function._propagateToListeners (http://localhost:54904/dart_sdk.js:33401:17)
> at _Future.new.[_completeWithValue] (http://localhost:54904/dart_sdk.js:33243:23)
> at async._AsyncCallbackEntry.new.callback (http://localhost:54904/dart_sdk.js:33266:35)
> at Object._microtaskLoop (http://localhost:54904/dart_sdk.js:38115:13)
> at _startMicrotaskLoop (http://localhost:54904/dart_sdk.js:38121:13)
> at http://localhost:54904/dart_sdk.js:33618:9

Yes this is what I get!

**Comment by harrbca** [comment]
Fixing this is above my abilities without introducing major security issues.  It looks like this used to be on the roadmap before it got staled out.  Any chance it can be resurrected?

**Comment by loetsphi** [comment]
@harrbca sadly, thats also our conclusion
If anyone has an idea how to solve it, feel free and let us know. Or even better make a pull request. 🧑‍💻
